from django.contrib import admin
from bmpdata.models import *

admin.site.register(Domain)
admin.site.register(PageTemplate)
admin.site.register(Page)
admin.site.register(Personnel)
admin.site.register(Imgs)
admin.site.register(Article)
admin.site.register(Library)
admin.site.register(Video)
admin.site.register(Contact)
admin.site.register(Plugin)
admin.site.register(Html)
admin.site.register(Files)
admin.site.register(Memberinfo)
admin.site.register(Meetissue)
admin.site.register(FileCollect)
admin.site.register(Sponsor)
admin.site.register(MemberPCollect)
admin.site.register(Ticket)
admin.site.register(Bill)
