# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-30 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='文章名称')),
                ('author', models.CharField(blank=True, default='admin', max_length=20, null=True, verbose_name='作者')),
                ('img', models.CharField(max_length=256, null=True, verbose_name='缩略图')),
                ('amount', models.IntegerField(blank=True, default=1, null=True, verbose_name='访问量')),
                ('summary', models.CharField(max_length=255, null=True, verbose_name='简介')),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
            options={
                'verbose_name_plural': '5-文章信息',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机')),
                ('company', models.CharField(max_length=128, null=True, verbose_name='公司')),
                ('department', models.CharField(max_length=64, null=True, verbose_name='部门')),
                ('position', models.CharField(max_length=64, null=True, verbose_name='职位')),
                ('interest', models.CharField(max_length=256, null=True, verbose_name='兴趣')),
                ('suggest', models.TextField(null=True, verbose_name='意见')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '6-加入我们信息',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='域名名称')),
                ('url', models.URLField(max_length=128, verbose_name='域名地址')),
                ('imgpath', models.CharField(blank=True, default='/data_new/', max_length=128, null=True, verbose_name='服务器图片路径')),
            ],
            options={
                'verbose_name_plural': '1-域名管理',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254, verbose_name='邮件地址')),
                ('passwd', models.CharField(max_length=128, null=True, verbose_name='密码')),
                ('smtp', models.CharField(max_length=128, null=True, verbose_name='地址')),
                ('port', models.IntegerField(null=True, verbose_name='端口')),
                ('auth', models.SmallIntegerField(choices=[(0, '不认证'), (1, '认证')], null=True, verbose_name='认证')),
                ('issh', models.SmallIntegerField(choices=[(0, '不加密'), (1, '加密')], null=True, verbose_name='加密')),
            ],
        ),
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='组名称')),
                ('effect', models.SmallIntegerField(choices=[(0, '接收'), (1, '发送')], default=0, verbose_name='作用')),
            ],
        ),
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('html', models.TextField(verbose_name='代码')),
            ],
        ),
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True, verbose_name='标题')),
                ('content', models.TextField(null=True, verbose_name='文本')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='链接')),
                ('img', models.CharField(max_length=255, verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '5-图片信息',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=1, verbose_name='权重')),
                ('name', models.CharField(max_length=64, verbose_name='库名称')),
                ('width', models.CharField(blank=True, default='100%', max_length=10, null=True, verbose_name='宽度')),
                ('height', models.CharField(blank=True, default='100%', max_length=10, null=True, verbose_name='高度')),
                ('space', models.IntegerField(blank=True, default=10000000, null=True, verbose_name='空间')),
            ],
            options={
                'verbose_name_plural': '3-模板库',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='页面名称')),
                ('url', models.CharField(max_length=256, verbose_name='链接')),
            ],
            options={
                'verbose_name_plural': '4-用户页面管理',
            },
        ),
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='模板名称')),
                ('img', models.CharField(max_length=255, verbose_name='分析图')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Domain')),
            ],
            options={
                'verbose_name_plural': '2-模板类型',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('ename', models.CharField(max_length=128, null=True, verbose_name='姓名拼音')),
                ('company', models.CharField(max_length=128, null=True, verbose_name='公司名称')),
                ('position', models.CharField(max_length=128, null=True, verbose_name='职位')),
                ('pic', models.CharField(max_length=256, null=True, verbose_name='头像')),
                ('summary', models.TextField(null=True, verbose_name='简介')),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Library')),
                ('ppl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Page')),
            ],
            options={
                'verbose_name_plural': '5-人员信息',
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='插件名称')),
                ('table', models.CharField(max_length=64, unique=True, verbose_name='表名称')),
            ],
            options={
                'verbose_name_plural': '3-插件库',
            },
        ),
        migrations.CreateModel(
            name='SysLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, verbose_name='操作用户')),
                ('log_type', models.SmallIntegerField(choices=[(1, 'Info'), (2, 'Debug'), (3, 'WARN'), (4, 'ERROR')], verbose_name='日志类型')),
                ('content', models.TextField(verbose_name='日志内容')),
                ('creat_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标题')),
                ('url', models.CharField(max_length=128, verbose_name='视频地址')),
                ('vl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Library')),
                ('vp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Page')),
            ],
            options={
                'verbose_name_plural': '5-视频信息',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='pp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.PageTemplate'),
        ),
        migrations.AddField(
            model_name='library',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Plugin'),
        ),
        migrations.AddField(
            model_name='library',
            name='ptl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.PageTemplate'),
        ),
        migrations.AddField(
            model_name='imgs',
            name='il',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Library'),
        ),
        migrations.AddField(
            model_name='imgs',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Page'),
        ),
        migrations.AddField(
            model_name='html',
            name='hl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Library'),
        ),
        migrations.AddField(
            model_name='html',
            name='hp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Page'),
        ),
        migrations.AddField(
            model_name='email',
            name='eg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.EmailGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set([('name', 'url')]),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('name', 'phone')]),
        ),
        migrations.AddField(
            model_name='article',
            name='al',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Library'),
        ),
        migrations.AddField(
            model_name='article',
            name='ap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='pagetemplate',
            unique_together=set([('domain', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('pp', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='imgs',
            unique_together=set([('ip', 'il', 'title')]),
        ),
    ]
