# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-08 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='meet',
            field=models.CharField(max_length=128, null=True, verbose_name='专场名称'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='meetaddr',
            field=models.CharField(max_length=255, null=True, verbose_name='会场地点'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='sdata',
            field=models.CharField(max_length=64, null=True, verbose_name='演讲日期'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='sintroduce',
            field=models.TextField(null=True, verbose_name='演讲介绍'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='stheme',
            field=models.CharField(max_length=255, null=True, verbose_name='演讲主题'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='stime',
            field=models.CharField(max_length=64, null=True, verbose_name='演讲时间'),
        ),
    ]
