# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-15 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0002_auto_20170908_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='文件名')),
                ('url', models.CharField(max_length=255, verbose_name='链接地址')),
                ('fl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Library')),
                ('fp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Page')),
            ],
        ),
        migrations.AlterModelOptions(
            name='html',
            options={'verbose_name_plural': '6-自定义字段'},
        ),
        migrations.AlterField(
            model_name='personnel',
            name='summary',
            field=models.TextField(null=True, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='files',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Personnel'),
        ),
        migrations.AlterUniqueTogether(
            name='files',
            unique_together=set([('fp', 'fl', 'name')]),
        ),
    ]
