# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0005_auto_20170919_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='td',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Domain'),
            preserve_default=False,
        ),
    ]
