# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0006_ticket_td'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': '文件下载管理'},
        ),
        migrations.AddField(
            model_name='article',
            name='ctime',
            field=models.TimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='files',
            name='ctime',
            field=models.TimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='html',
            name='ctime',
            field=models.TimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='imgs',
            name='ctime',
            field=models.TimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='ctime',
            field=models.TimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='video',
            name='ctime',
            field=models.TimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
