# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0007_auto_20170920_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='ctime',
        ),
    ]
