# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0008_remove_personnel_ctime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgs',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='video',
            name='ctime',
        ),
        migrations.AddField(
            model_name='personnel',
            name='ctime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ctime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='files',
            name='ctime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='html',
            name='ctime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='ctime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='创建时间'),
        ),
    ]
