# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0011_video_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='other',
            field=models.CharField(default='', max_length=256, verbose_name='备注信息'),
            preserve_default=False,
        ),
    ]
