# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0012_library_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名')),
                ('order_time', models.CharField(max_length=64, verbose_name='订单时间')),
                ('order_nub', models.CharField(max_length=64, verbose_name='订单号')),
                ('ticket', models.CharField(max_length=64, verbose_name='门票类型')),
                ('price', models.FloatField(verbose_name='门票价格')),
                ('channel', models.CharField(max_length=64, verbose_name='渠道')),
                ('channel_code', models.CharField(max_length=64, verbose_name='渠道编码')),
                ('sign_staus', models.SmallIntegerField(choices=[(0, '未签到'), (1, '已签到')], verbose_name='签到状态')),
                ('sign_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='签到时间')),
                ('remarks', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '订单信息',
            },
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='company',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='position',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='职位'),
        ),
    ]
