# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0013_auto_20170920_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='code',
            field=models.CharField(default='', max_length=64, verbose_name='签到码'),
            preserve_default=False,
        ),
    ]
