# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-21 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0014_bill_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='ctime',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='channel',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='渠道'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='channel_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='渠道编码'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='签到码'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order_nub',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='订单时间'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sign_staus',
            field=models.SmallIntegerField(choices=[(0, '未签到'), (1, '已签到')], default=0, verbose_name='签到状态'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='sex',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (0, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set([('order_nub', 'code', 'phone')]),
        ),
    ]
