# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-22 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0015_auto_20170921_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetissue',
            name='ctime',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='ctime',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
