# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0017_auto_20170922_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bd',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Domain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetissue',
            name='dm',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Domain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='ds',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='bmpdata.Domain'),
            preserve_default=False,
        ),
    ]
