# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-22 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0019_auto_20170922_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetissue',
            name='photo',
            field=models.TextField(verbose_name='照片'),
        ),
    ]
