# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-25 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpdata', '0023_auto_20170924_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetissue',
            name='speech_experience',
            field=models.TextField(blank=True, null=True, verbose_name='演讲经验'),
        ),
        migrations.AlterField(
            model_name='meetissue',
            name='summary',
            field=models.CharField(max_length=256, verbose_name='个人简介'),
        ),
    ]
